$(function(){$(".entry-text,.post-title,.clear,.photo-caption,.question").minEmoji()});document.write("<style>.em{zoom:"+6.25*parseInt($("body").css("font-size"))+"%;}</style>");
(function(){function e(){}function f(a,b){for(var c=a.length;c--;)if(a[c].listener===b)return c;return-1}function l(a){return function(){return this[a].apply(this,arguments)}}var g=e.prototype,d=this,c=d.EventEmitter;g.getListeners=function(a){var b,c,h=this._getEvents();if("object"==typeof a)for(c in b={},h)h.hasOwnProperty(c)&&a.test(c)&&(b[c]=h[c]);else b=h[a]||(h[a]=[]);return b};g.flattenListeners=function(a){var b,c=[];for(b=0;a.length>b;b+=1)c.push(a[b].listener);return c};g.getListenersAsObject=
function(a){var b,c=this.getListeners(a);return c instanceof Array&&(b={},b[a]=c),b||c};g.addListener=function(a,b){var c,h=this.getListenersAsObject(a),d="object"==typeof b;for(c in h)h.hasOwnProperty(c)&&-1===f(h[c],b)&&h[c].push(d?b:{listener:b,once:!1});return this};g.on=l("addListener");g.addOnceListener=function(a,b){return this.addListener(a,{listener:b,once:!0})};g.once=l("addOnceListener");g.defineEvent=function(a){return this.getListeners(a),this};g.defineEvents=function(a){for(var b=0;a.length>
b;b+=1)this.defineEvent(a[b]);return this};g.removeListener=function(a,b){var c,h,d=this.getListenersAsObject(a);for(h in d)d.hasOwnProperty(h)&&(c=f(d[h],b),-1!==c&&d[h].splice(c,1));return this};g.off=l("removeListener");g.addListeners=function(a,b){return this.manipulateListeners(!1,a,b)};g.removeListeners=function(a,b){return this.manipulateListeners(!0,a,b)};g.manipulateListeners=function(a,b,c){var d,e,f=a?this.removeListener:this.addListener;a=a?this.removeListeners:this.addListeners;if("object"!=
typeof b||b instanceof RegExp)for(d=c.length;d--;)f.call(this,b,c[d]);else for(d in b)b.hasOwnProperty(d)&&(e=b[d])&&("function"==typeof e?f.call(this,d,e):a.call(this,d,e));return this};g.removeEvent=function(a){var b,c=typeof a,d=this._getEvents();if("string"===c)delete d[a];else if("object"===c)for(b in d)d.hasOwnProperty(b)&&a.test(b)&&delete d[b];else delete this._events;return this};g.removeAllListeners=l("removeEvent");g.emitEvent=function(a,b){var c,d,e,f,g=this.getListenersAsObject(a);for(e in g)if(g.hasOwnProperty(e))for(d=
g[e].length;d--;)c=g[e][d],!0===c.once&&this.removeListener(a,c.listener),f=c.listener.apply(this,b||[]),f===this._getOnceReturnValue()&&this.removeListener(a,c.listener);return this};g.trigger=l("emitEvent");g.emit=function(a){var b=Array.prototype.slice.call(arguments,1);return this.emitEvent(a,b)};g.setOnceReturnValue=function(a){return this._onceReturnValue=a,this};g._getOnceReturnValue=function(){return this.hasOwnProperty("_onceReturnValue")?this._onceReturnValue:!0};g._getEvents=function(){return this._events||
(this._events={})};e.noConflict=function(){return d.EventEmitter=c,e};"function"==typeof define&&define.amd?define("eventEmitter/EventEmitter",[],function(){return e}):"object"==typeof module&&module.exports?module.exports=e:this.EventEmitter=e}).call(this);
(function(e){function f(c){var a=e.event;return a.target=a.target||a.srcElement||c,a}var l=document.documentElement,g=function(){};l.addEventListener?g=function(c,a,b){c.addEventListener(a,b,!1)}:l.attachEvent&&(g=function(c,a,b){c[a+b]=b.handleEvent?function(){var a=f(c);b.handleEvent.call(b,a)}:function(){var a=f(c);b.call(c,a)};c.attachEvent("on"+a,c[a+b])});var d=function(){};l.removeEventListener?d=function(c,a,b){c.removeEventListener(a,b,!1)}:l.detachEvent&&(d=function(c,a,b){c.detachEvent("on"+
a,c[a+b]);try{delete c[a+b]}catch(d){c[a+b]=void 0}});l={bind:g,unbind:d};"function"==typeof define&&define.amd?define("eventie/eventie",l):e.eventie=l})(this);
(function(e,f){"function"==typeof define&&define.amd?define(["eventEmitter/EventEmitter","eventie/eventie"],function(l,g){return f(e,l,g)}):"object"==typeof exports?module.exports=f(e,require("wolfy87-eventemitter"),require("eventie")):e.imagesLoaded=f(e,e.EventEmitter,e.eventie)})(window,function(e,f,l){function g(a,b){for(var c in b)a[c]=b[c];return a}function d(a){var b=[];if("[object Array]"===n.call(a))b=a;else if("number"==typeof a.length)for(var c=0,d=a.length;d>c;c++)b.push(a[c]);else b.push(a);
return b}function c(a,b,h){if(!(this instanceof c))return new c(a,b);"string"==typeof a&&(a=document.querySelectorAll(a));this.elements=d(a);this.options=g({},this.options);"function"==typeof b?h=b:g(this.options,b);h&&this.on("always",h);this.getImages();p&&(this.jqDeferred=new p.Deferred);var e=this;setTimeout(function(){e.check()})}function a(a){this.img=a}function b(a){this.src=a;w[a]=this}var p=e.jQuery,h=e.console,t=void 0!==h,n=Object.prototype.toString;c.prototype=new f;c.prototype.options=
{};c.prototype.getImages=function(){this.images=[];for(var a=0,b=this.elements.length;b>a;a++){var c=this.elements[a];"IMG"===c.nodeName&&this.addImage(c);var d=c.nodeType;if(d&&(1===d||9===d||11===d))for(var c=c.querySelectorAll("img"),d=0,h=c.length;h>d;d++)this.addImage(c[d])}};c.prototype.addImage=function(b){b=new a(b);this.images.push(b)};c.prototype.check=function(){function a(e,p){return b.options.debug&&t&&h.log("confirm",e,p),b.progress(e),c++,c===d&&b.complete(),!0}var b=this,c=0,d=this.images.length;
if(this.hasAnyBroken=!1,!d)return this.complete(),void 0;for(var e=0;d>e;e++){var p=this.images[e];p.on("confirm",a);p.check()}};c.prototype.progress=function(a){this.hasAnyBroken=this.hasAnyBroken||!a.isLoaded;var b=this;setTimeout(function(){b.emit("progress",b,a);b.jqDeferred&&b.jqDeferred.notify&&b.jqDeferred.notify(b,a)})};c.prototype.complete=function(){var a=this.hasAnyBroken?"fail":"done";this.isComplete=!0;var b=this;setTimeout(function(){if(b.emit(a,b),b.emit("always",b),b.jqDeferred)b.jqDeferred[b.hasAnyBroken?
"reject":"resolve"](b)})};p&&(p.fn.imagesLoaded=function(b,a){return(new c(this,b,a)).jqDeferred.promise(p(this))});a.prototype=new f;a.prototype.check=function(){var a=w[this.img.src]||new b(this.img.src);if(a.isConfirmed)return this.confirm(a.isLoaded,"cached was confirmed"),void 0;if(this.img.complete&&void 0!==this.img.naturalWidth)return this.confirm(0!==this.img.naturalWidth,"naturalWidth"),void 0;var c=this;a.on("confirm",function(a,b){return c.confirm(a.isLoaded,b),!0});a.check()};a.prototype.confirm=
function(a,b){this.isLoaded=a;this.emit("confirm",this,b)};var w={};return b.prototype=new f,b.prototype.check=function(){if(!this.isChecked){var a=new Image;l.bind(a,"load",this);l.bind(a,"error",this);a.src=this.src;this.isChecked=!0}},b.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)},b.prototype.onload=function(a){this.confirm(!0,"onload");this.unbindProxyEvents(a)},b.prototype.onerror=function(a){this.confirm(!1,"onerror");this.unbindProxyEvents(a)},b.prototype.confirm=
function(a,b){this.isConfirmed=!0;this.isLoaded=a;this.emit("confirm",this,b)},b.prototype.unbindProxyEvents=function(a){l.unbind(a.target,"load",this);l.unbind(a.target,"error",this)},c});
!function(e){function f(){}function l(d){function c(a){a.prototype.option||(a.prototype.option=function(a){d.isPlainObject(a)&&(this.options=d.extend(!0,this.options,a))})}function a(a,c){d.fn[a]=function(e){if("string"==typeof e){for(var f=g.call(arguments,1),l=0,A=this.length;A>l;l++){var m=d.data(this[l],a);if(m)if(d.isFunction(m[e])&&"_"!==e.charAt(0)){if(m=m[e].apply(m,f),void 0!==m)return m}else b("no such method '"+e+"' for "+a+" instance");else b("cannot call methods on "+a+" prior to initialization; attempted to call '"+
e+"'")}return this}return this.each(function(){var b=d.data(this,a);b?(b.option(e),b._init()):(b=new c(this,e),d.data(this,a,b))})}}if(d){var b="undefined"==typeof console?f:function(a){console.error(a)};return d.bridget=function(b,d){c(d);a(b,d)},d.bridget}}var g=Array.prototype.slice;"function"==typeof define&&define.amd?define("jquery-bridget/jquery.bridget",["jquery"],l):l("object"==typeof exports?require("jquery"):e.jQuery)}(window);
(function(e){function f(c){var a=e.event;return a.target=a.target||a.srcElement||c,a}var l=document.documentElement,g=function(){};l.addEventListener?g=function(c,a,b){c.addEventListener(a,b,!1)}:l.attachEvent&&(g=function(c,a,b){c[a+b]=b.handleEvent?function(){var a=f(c);b.handleEvent.call(b,a)}:function(){var a=f(c);b.call(c,a)};c.attachEvent("on"+a,c[a+b])});var d=function(){};l.removeEventListener?d=function(c,a,b){c.removeEventListener(a,b,!1)}:l.detachEvent&&(d=function(c,a,b){c.detachEvent("on"+
a,c[a+b]);try{delete c[a+b]}catch(d){c[a+b]=void 0}});l={bind:g,unbind:d};"function"==typeof define&&define.amd?define("eventie/eventie",l):"object"==typeof exports?module.exports=l:e.eventie=l})(this);
(function(e){function f(b){"function"==typeof b&&(f.isReady?b():a.push(b))}function l(a){a="readystatechange"===a.type&&"complete"!==c.readyState;f.isReady||a||g()}function g(){f.isReady=!0;for(var b=0,c=a.length;c>b;b++)(0,a[b])()}function d(a){return"complete"===c.readyState?g():(a.bind(c,"DOMContentLoaded",l),a.bind(c,"readystatechange",l),a.bind(e,"load",l)),f}var c=e.document,a=[];f.isReady=!1;"function"==typeof define&&define.amd?define("doc-ready/doc-ready",["eventie/eventie"],d):"object"==
typeof exports?module.exports=d(require("eventie")):e.docReady=d(e.eventie)})(window);
(function(){function e(){}function f(a,b){for(var c=a.length;c--;)if(a[c].listener===b)return c;return-1}function l(a){return function(){return this[a].apply(this,arguments)}}var g=e.prototype,d=this,c=d.EventEmitter;g.getListeners=function(a){var b,c,d=this._getEvents();if(a instanceof RegExp)for(c in b={},d)d.hasOwnProperty(c)&&a.test(c)&&(b[c]=d[c]);else b=d[a]||(d[a]=[]);return b};g.flattenListeners=function(a){var b,c=[];for(b=0;b<a.length;b+=1)c.push(a[b].listener);return c};g.getListenersAsObject=
function(a){var b,c=this.getListeners(a);return c instanceof Array&&(b={},b[a]=c),b||c};g.addListener=function(a,b){var c,d=this.getListenersAsObject(a),e="object"==typeof b;for(c in d)d.hasOwnProperty(c)&&-1===f(d[c],b)&&d[c].push(e?b:{listener:b,once:!1});return this};g.on=l("addListener");g.addOnceListener=function(a,b){return this.addListener(a,{listener:b,once:!0})};g.once=l("addOnceListener");g.defineEvent=function(a){return this.getListeners(a),this};g.defineEvents=function(a){for(var b=0;b<
a.length;b+=1)this.defineEvent(a[b]);return this};g.removeListener=function(a,b){var c,d,e=this.getListenersAsObject(a);for(d in e)e.hasOwnProperty(d)&&(c=f(e[d],b),-1!==c&&e[d].splice(c,1));return this};g.off=l("removeListener");g.addListeners=function(a,b){return this.manipulateListeners(!1,a,b)};g.removeListeners=function(a,b){return this.manipulateListeners(!0,a,b)};g.manipulateListeners=function(a,b,c){var d,e,f=a?this.removeListener:this.addListener;a=a?this.removeListeners:this.addListeners;
if("object"!=typeof b||b instanceof RegExp)for(d=c.length;d--;)f.call(this,b,c[d]);else for(d in b)b.hasOwnProperty(d)&&(e=b[d])&&("function"==typeof e?f.call(this,d,e):a.call(this,d,e));return this};g.removeEvent=function(a){var b,c=typeof a,d=this._getEvents();if("string"===c)delete d[a];else if(a instanceof RegExp)for(b in d)d.hasOwnProperty(b)&&a.test(b)&&delete d[b];else delete this._events;return this};g.removeAllListeners=l("removeEvent");g.emitEvent=function(a,b){var c,d,e,f,g=this.getListenersAsObject(a);
for(e in g)if(g.hasOwnProperty(e))for(d=g[e].length;d--;)c=g[e][d],!0===c.once&&this.removeListener(a,c.listener),f=c.listener.apply(this,b||[]),f===this._getOnceReturnValue()&&this.removeListener(a,c.listener);return this};g.trigger=l("emitEvent");g.emit=function(a){var b=Array.prototype.slice.call(arguments,1);return this.emitEvent(a,b)};g.setOnceReturnValue=function(a){return this._onceReturnValue=a,this};g._getOnceReturnValue=function(){return this.hasOwnProperty("_onceReturnValue")?this._onceReturnValue:
!0};g._getEvents=function(){return this._events||(this._events={})};e.noConflict=function(){return d.EventEmitter=c,e};"function"==typeof define&&define.amd?define("eventEmitter/EventEmitter",[],function(){return e}):"object"==typeof module&&module.exports?module.exports=e:d.EventEmitter=e}).call(this);
(function(e){function f(d){if(d){if("string"==typeof g[d])return d;d=d.charAt(0).toUpperCase()+d.slice(1);for(var c,a=0,b=l.length;b>a;a++)if(c=l[a]+d,"string"==typeof g[c])return c}}var l=["Webkit","Moz","ms","Ms","O"],g=document.documentElement.style;"function"==typeof define&&define.amd?define("get-style-property/get-style-property",[],function(){return f}):"object"==typeof exports?module.exports=f:e.getStyleProperty=f})(window);
(function(e){function f(a){var b=parseFloat(a);return-1===a.indexOf("%")&&!isNaN(b)&&b}function l(){}function g(a){function b(){if(!n){n=!0;var b=e.getComputedStyle;if(g=function(){var a=b?function(a){return b(a,null)}:function(a){return a.currentStyle};return function(b){b=a(b);return b||d("Style returned "+b+". Are you running this code in a hidden iframe on Firefox? See http://bit.ly/getsizebug1"),b}}(),h=a("boxSizing")){var c=document.createElement("div");c.style.width="200px";c.style.padding=
"1px 2px 3px 4px";c.style.borderStyle="solid";c.style.borderWidth="1px 2px 3px 4px";c.style[h]="border-box";var m=document.body||document.documentElement;m.appendChild(c);var B=g(c);l=200===f(B.width);m.removeChild(c)}}}var g,h,l,n=!1;return function(a){if(b(),"string"==typeof a&&(a=document.querySelector(a)),a&&"object"==typeof a&&a.nodeType){var d=g(a);if("none"===d.display){for(var m={width:0,height:0,innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0},d=0,n=c.length;n>d;d++)m[c[d]]=0;return m}m=
{};m.width=a.offsetWidth;m.height=a.offsetHeight;for(var n=m.isBorderBox=!(!h||!d[h]||"border-box"!==d[h]),v=0,C=c.length;C>v;v++){var z=c[v],k=d[z];var u=a,x=k;if(e.getComputedStyle||-1===x.indexOf("%"))k=x;else var k=u.style,y=k.left,q=u.runtimeStyle,r=q&&q.left,k=(r&&(q.left=u.currentStyle.left),k.left=x,x=k.pixelLeft,k.left=y,r&&(q.left=r),x);u=parseFloat(k);m[z]=isNaN(u)?0:u}a=m.paddingLeft+m.paddingRight;v=m.paddingTop+m.paddingBottom;C=m.marginLeft+m.marginRight;z=m.marginTop+m.marginBottom;
u=m.borderLeftWidth+m.borderRightWidth;x=m.borderTopWidth+m.borderBottomWidth;n=n&&l;k=f(d.width);!1!==k&&(m.width=k+(n?0:a+u));d=f(d.height);return!1!==d&&(m.height=d+(n?0:v+x)),m.innerWidth=m.width-(a+u),m.innerHeight=m.height-(v+x),m.outerWidth=m.width+C,m.outerHeight=m.height+z,m}}}var d="undefined"==typeof console?l:function(a){console.error(a)},c="paddingLeft paddingRight paddingTop paddingBottom marginLeft marginRight marginTop marginBottom borderLeftWidth borderRightWidth borderTopWidth borderBottomWidth".split(" ");
"function"==typeof define&&define.amd?define("get-size/get-size",["get-style-property/get-style-property"],g):"object"==typeof exports?module.exports=g(require("desandro-get-style-property")):e.getSize=g(e.getStyleProperty)})(window);
(function(e){function f(a,d){return a[c](d)}function l(a,c){a.parentNode||document.createDocumentFragment().appendChild(a);for(var d=a.parentNode.querySelectorAll(c),e=0,f=d.length;f>e;e++)if(d[e]===a)return!0;return!1}function g(a,c){a.parentNode||document.createDocumentFragment().appendChild(a);return f(a,c)}var d,c=function(){if(e.matchesSelector)return"matchesSelector";for(var a=["webkit","moz","ms","o"],c=0,d=a.length;d>c;c++){var f=a[c]+"MatchesSelector";if(e[f])return f}}();if(c){var a=document.createElement("div");
d=f(a,"div")?f:g}else d=l;"function"==typeof define&&define.amd?define("matches-selector/matches-selector",[],function(){return d}):"object"==typeof exports?module.exports=d:window.matchesSelector=d})(Element.prototype);
(function(e){function f(a,b){for(var c in b)a[c]=b[c];return a}function l(a){return a.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()})}function g(a,b,d){function e(a,b){a&&(this.element=a,this.layout=b,this.position={x:0,y:0},this._create())}var g=d("transition"),n=d("transform"),w=g&&n,A=!!d("perspective"),m={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"otransitionend",transition:"transitionend"}[g],B=["transform","transition","transitionDuration","transitionProperty"],
v=function(){for(var a={},b=0,c=B.length;c>b;b++){var e=B[b],f=d(e);f&&f!==e&&(a[e]=f)}return a}();f(e.prototype,a.prototype);e.prototype._create=function(){this._transn={ingProperties:{},clean:{},onEnd:{}};this.css({position:"absolute"})};e.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)};e.prototype.getSize=function(){this.size=b(this.element)};e.prototype.css=function(a){var b=this.element.style,c;for(c in a)b[v[c]||c]=a[c]};e.prototype.getPosition=function(){var a=c(this.element),
b=this.layout.options,d=b.isOriginLeft,b=b.isOriginTop,e=parseInt(a[d?"left":"right"],10),a=parseInt(a[b?"top":"bottom"],10),e=isNaN(e)?0:e,a=isNaN(a)?0:a,f=this.layout.size,e=e-(d?f.paddingLeft:f.paddingRight),a=a-(b?f.paddingTop:f.paddingBottom);this.position.x=e;this.position.y=a};e.prototype.layoutPosition=function(){var a=this.layout.size,b=this.layout.options,c={};b.isOriginLeft?(c.left=this.position.x+a.paddingLeft+"px",c.right=""):(c.right=this.position.x+a.paddingRight+"px",c.left="");b.isOriginTop?
(c.top=this.position.y+a.paddingTop+"px",c.bottom=""):(c.bottom=this.position.y+a.paddingBottom+"px",c.top="");this.css(c);this.emitEvent("layout",[this])};var C=A?function(a,b){return"translate3d("+a+"px, "+b+"px, 0)"}:function(a,b){return"translate("+a+"px, "+b+"px)"};e.prototype._transitionTo=function(a,b){this.getPosition();var c=this.position.x,d=this.position.y,e=parseInt(a,10),f=parseInt(b,10),e=e===this.position.x&&f===this.position.y;if(this.setPosition(a,b),e&&!this.isTransitioning)return void this.layoutPosition();
c=a-c;d=b-d;e={};f=this.layout.options;c=f.isOriginLeft?c:-c;d=f.isOriginTop?d:-d;e.transform=C(c,d);this.transition({to:e,onTransitionEnd:{transform:this.layoutPosition},isCleaning:!0})};e.prototype.goTo=function(a,b){this.setPosition(a,b);this.layoutPosition()};e.prototype.moveTo=w?e.prototype._transitionTo:e.prototype.goTo;e.prototype.setPosition=function(a,b){this.position.x=parseInt(a,10);this.position.y=parseInt(b,10)};e.prototype._nonTransition=function(a){this.css(a.to);a.isCleaning&&this._removeStyles(a.to);
for(var b in a.onTransitionEnd)a.onTransitionEnd[b].call(this)};e.prototype._transition=function(a){if(!parseFloat(this.layout.options.transitionDuration))return void this._nonTransition(a);var b=this._transn,c;for(c in a.onTransitionEnd)b.onEnd[c]=a.onTransitionEnd[c];for(c in a.to)b.ingProperties[c]=!0,a.isCleaning&&(b.clean[c]=!0);a.from&&this.css(a.from);this.enableTransition(a.to);this.css(a.to);this.isTransitioning=!0};var z=n&&l(n)+",opacity";e.prototype.enableTransition=function(){this.isTransitioning||
(this.css({transitionProperty:z,transitionDuration:this.layout.options.transitionDuration}),this.element.addEventListener(m,this,!1))};e.prototype.transition=e.prototype[g?"_transition":"_nonTransition"];e.prototype.onwebkitTransitionEnd=function(a){this.ontransitionend(a)};e.prototype.onotransitionend=function(a){this.ontransitionend(a)};var k={"-webkit-transform":"transform","-moz-transform":"transform","-o-transform":"transform"};e.prototype.ontransitionend=function(a){if(a.target===this.element){var b=
this._transn,c=k[a.propertyName]||a.propertyName;delete b.ingProperties[c];var d;a:{d=b.ingProperties;for(var e in d){d=!1;break a}d=!0}if(d&&this.disableTransition(),c in b.clean&&(this.element.style[a.propertyName]="",delete b.clean[c]),c in b.onEnd)b.onEnd[c].call(this),delete b.onEnd[c];this.emitEvent("transitionEnd",[this])}};e.prototype.disableTransition=function(){this.removeTransitionStyles();this.element.removeEventListener(m,this,!1);this.isTransitioning=!1};e.prototype._removeStyles=function(a){var b=
{},c;for(c in a)b[c]="";this.css(b)};var u={transitionProperty:"",transitionDuration:""};return e.prototype.removeTransitionStyles=function(){this.css(u)},e.prototype.removeElem=function(){this.element.parentNode.removeChild(this.element);this.emitEvent("remove",[this])},e.prototype.remove=function(){if(!g||!parseFloat(this.layout.options.transitionDuration))return void this.removeElem();var a=this;this.on("transitionEnd",function(){return a.removeElem(),!0});this.hide()},e.prototype.reveal=function(){delete this.isHidden;
this.css({display:""});var a=this.layout.options;this.transition({from:a.hiddenStyle,to:a.visibleStyle,isCleaning:!0})},e.prototype.hide=function(){this.isHidden=!0;this.css({display:""});var a=this.layout.options;this.transition({from:a.visibleStyle,to:a.hiddenStyle,isCleaning:!0,onTransitionEnd:{opacity:function(){this.isHidden&&this.css({display:"none"})}}})},e.prototype.destroy=function(){this.css({position:"",left:"",right:"",top:"",bottom:"",transition:"",transform:""})},e}var d=e.getComputedStyle,
c=d?function(a){return d(a,null)}:function(a){return a.currentStyle};"function"==typeof define&&define.amd?define("outlayer/item",["eventEmitter/EventEmitter","get-size/get-size","get-style-property/get-style-property"],g):"object"==typeof exports?module.exports=g(require("wolfy87-eventemitter"),require("get-size"),require("desandro-get-style-property")):(e.Outlayer={},e.Outlayer.Item=g(e.EventEmitter,e.getSize,e.getStyleProperty))})(window);
(function(e){function f(a,b){for(var c in b)a[c]=b[c];return a}function l(a){var b=[];if("[object Array]"===t.call(a))b=a;else if(a&&"number"==typeof a.length)for(var c=0,d=a.length;d>c;c++)b.push(a[c]);else b.push(a);return b}function g(a,b){var c=w(b,a);-1!==c&&b.splice(c,1)}function d(a){return a.replace(/(.)([A-Z])/g,function(a,b,c){return b+"-"+c}).toLowerCase()}function c(c,m,t,v,w,z){function k(c,d){if("string"==typeof c&&(c=a.querySelector(c)),!c||!n(c))return void(b&&b.error("Bad "+this.constructor.namespace+
" element: "+c));this.element=c;this.options=f({},this.constructor.defaults);this.option(d);var e=++u;this.element.outlayerGUID=e;x[e]=this;this._create();this.options.isInitLayout&&this.layout()}var u=0,x={};return k.namespace="outlayer",k.Item=z,k.defaults={containerStyle:{position:"relative"},isInitLayout:!0,isOriginLeft:!0,isOriginTop:!0,isResizeBound:!0,isResizingContainer:!0,transitionDuration:"0.4s",hiddenStyle:{opacity:0,transform:"scale(0.001)"},visibleStyle:{opacity:1,transform:"scale(1)"}},
f(k.prototype,t.prototype),k.prototype.option=function(a){f(this.options,a)},k.prototype._create=function(){this.reloadItems();this.stamps=[];this.stamp(this.options.stamp);f(this.element.style,this.options.containerStyle);this.options.isResizeBound&&this.bindResize()},k.prototype.reloadItems=function(){this.items=this._itemize(this.element.children)},k.prototype._itemize=function(a){a=this._filterFindItemElements(a);for(var b=this.constructor.Item,c=[],d=0,e=a.length;e>d;d++){var f=new b(a[d],this);
c.push(f)}return c},k.prototype._filterFindItemElements=function(a){a=l(a);for(var c=this.options.itemSelector,b=[],d=0,e=a.length;e>d;d++){var f=a[d];if(n(f))if(c){w(f,c)&&b.push(f);for(var f=f.querySelectorAll(c),E=0,g=f.length;g>E;E++)b.push(f[E])}else b.push(f)}return b},k.prototype.getItemElements=function(){for(var a=[],b=0,c=this.items.length;c>b;b++)a.push(this.items[b].element);return a},k.prototype.layout=function(){this._resetLayout();this._manageStamps();this.layoutItems(this.items,void 0!==
this.options.isLayoutInstant?this.options.isLayoutInstant:!this._isLayoutInited);this._isLayoutInited=!0},k.prototype._init=k.prototype.layout,k.prototype._resetLayout=function(){this.getSize()},k.prototype.getSize=function(){this.size=v(this.element)},k.prototype._getMeasurement=function(a,b){var c,d=this.options[a];d?("string"==typeof d?c=this.element.querySelector(d):n(d)&&(c=d),this[a]=c?v(c)[b]:d):this[a]=0},k.prototype.layoutItems=function(a,c){a=this._getItemsForLayout(a);this._layoutItems(a,
c);this._postLayout()},k.prototype._getItemsForLayout=function(a){for(var c=[],b=0,d=a.length;d>b;b++){var e=a[b];e.isIgnored||c.push(e)}return c},k.prototype._layoutItems=function(a,c){function b(){d.emitEvent("layoutComplete",[d,a])}var d=this;if(!a||!a.length)return void b();this._itemsOn(a,"layout",b);for(var e=[],f=0,E=a.length;E>f;f++){var g=a[f],h=this._getItemLayoutPosition(g);h.item=g;h.isInstant=c||g.isLayoutInstant;e.push(h)}this._processLayoutQueue(e)},k.prototype._getItemLayoutPosition=
function(){return{x:0,y:0}},k.prototype._processLayoutQueue=function(a){for(var c=0,b=a.length;b>c;c++){var d=a[c];this._positionItem(d.item,d.x,d.y,d.isInstant)}},k.prototype._positionItem=function(a,c,b,d){d?a.goTo(c,b):a.moveTo(c,b)},k.prototype._postLayout=function(){this.resizeContainer()},k.prototype.resizeContainer=function(){if(this.options.isResizingContainer){var a=this._getContainerSize();a&&(this._setContainerMeasure(a.width,!0),this._setContainerMeasure(a.height,!1))}},k.prototype._getContainerSize=
h,k.prototype._setContainerMeasure=function(a,c){if(void 0!==a){var b=this.size;b.isBorderBox&&(a+=c?b.paddingLeft+b.paddingRight+b.borderLeftWidth+b.borderRightWidth:b.paddingBottom+b.paddingTop+b.borderTopWidth+b.borderBottomWidth);a=Math.max(a,0);this.element.style[c?"width":"height"]=a+"px"}},k.prototype._itemsOn=function(a,b,c){function d(){return e++,e===f&&c.call(E),!0}for(var e=0,f=a.length,E=this,g=0,h=a.length;h>g;g++)a[g].on(b,d)},k.prototype.ignore=function(a){(a=this.getItem(a))&&(a.isIgnored=
!0)},k.prototype.unignore=function(a){(a=this.getItem(a))&&delete a.isIgnored},k.prototype.stamp=function(a){if(a=this._find(a)){this.stamps=this.stamps.concat(a);for(var b=0,c=a.length;c>b;b++)this.ignore(a[b])}},k.prototype.unstamp=function(a){if(a=this._find(a))for(var b=0,c=a.length;c>b;b++){var d=a[b];g(d,this.stamps);this.unignore(d)}},k.prototype._find=function(a){return a?("string"==typeof a&&(a=this.element.querySelectorAll(a)),l(a)):void 0},k.prototype._manageStamps=function(){if(this.stamps&&
this.stamps.length){this._getBoundingRect();for(var a=0,b=this.stamps.length;b>a;a++)this._manageStamp(this.stamps[a])}},k.prototype._getBoundingRect=function(){var a=this.element.getBoundingClientRect(),b=this.size;this._boundingRect={left:a.left+b.paddingLeft+b.borderLeftWidth,top:a.top+b.paddingTop+b.borderTopWidth,right:a.right-(b.paddingRight+b.borderRightWidth),bottom:a.bottom-(b.paddingBottom+b.borderBottomWidth)}},k.prototype._manageStamp=h,k.prototype._getElementOffset=function(a){var b=
a.getBoundingClientRect(),c=this._boundingRect;a=v(a);return{left:b.left-c.left-a.marginLeft,top:b.top-c.top-a.marginTop,right:c.right-b.right-a.marginRight,bottom:c.bottom-b.bottom-a.marginBottom}},k.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)},k.prototype.bindResize=function(){this.isResizeBound||(c.bind(e,"resize",this),this.isResizeBound=!0)},k.prototype.unbindResize=function(){this.isResizeBound&&c.unbind(e,"resize",this);this.isResizeBound=!1},k.prototype.onresize=
function(){this.resizeTimeout&&clearTimeout(this.resizeTimeout);var a=this;this.resizeTimeout=setTimeout(function(){a.resize();delete a.resizeTimeout},100)},k.prototype.resize=function(){this.isResizeBound&&this.needsResizeLayout()&&this.layout()},k.prototype.needsResizeLayout=function(){var a=v(this.element);return this.size&&a&&a.innerWidth!==this.size.innerWidth},k.prototype.addItems=function(a){a=this._itemize(a);return a.length&&(this.items=this.items.concat(a)),a},k.prototype.appended=function(a){a=
this.addItems(a);a.length&&(this.layoutItems(a,!0),this.reveal(a))},k.prototype.prepended=function(a){a=this._itemize(a);if(a.length){var b=this.items.slice(0);this.items=a.concat(b);this._resetLayout();this._manageStamps();this.layoutItems(a,!0);this.reveal(a);this.layoutItems(b)}},k.prototype.reveal=function(a){var b=a&&a.length;if(b)for(var c=0;b>c;c++)a[c].reveal()},k.prototype.hide=function(a){var b=a&&a.length;if(b)for(var c=0;b>c;c++)a[c].hide()},k.prototype.getItem=function(a){for(var b=0,
c=this.items.length;c>b;b++){var d=this.items[b];if(d.element===a)return d}},k.prototype.getItems=function(a){if(a&&a.length){for(var b=[],c=0,d=a.length;d>c;c++){var e=this.getItem(a[c]);e&&b.push(e)}return b}},k.prototype.remove=function(a){a=l(a);var b=this.getItems(a);if(b&&b.length){this._itemsOn(b,"remove",function(){this.emitEvent("removeComplete",[this,b])});a=0;for(var c=b.length;c>a;a++){var d=b[a];d.remove();g(d,this.items)}}},k.prototype.destroy=function(){var a=this.element.style;a.height=
"";a.position="";a.width="";for(var a=0,b=this.items.length;b>a;a++)this.items[a].destroy();this.unbindResize();delete x[this.element.outlayerGUID];delete this.element.outlayerGUID;p&&p.removeData(this.element,this.constructor.namespace)},k.data=function(a){return(a=a&&a.outlayerGUID)&&x[a]},k.create=function(c,e){function g(){k.apply(this,arguments)}return Object.create?g.prototype=Object.create(k.prototype):f(g.prototype,k.prototype),g.prototype.constructor=g,g.defaults=f({},k.defaults),f(g.defaults,
e),g.prototype.settings={},g.namespace=c,g.data=k.data,g.Item=function(){z.apply(this,arguments)},g.Item.prototype=new z,m(function(){for(var e=d(c),f=a.querySelectorAll(".js-"+e),e="data-"+e+"-options",D=0,E=f.length;E>D;D++){var h,l=f[D],k=l.getAttribute(e);try{h=k&&JSON.parse(k)}catch(m){b&&b.error("Error parsing "+e+" on "+l.nodeName.toLowerCase()+(l.id?"#"+l.id:"")+": "+m);continue}k=new g(l,h);p&&p.data(l,c,k)}}),p&&p.bridget&&p.bridget(c,g),g},k.Item=z,k}var a=e.document,b=e.console,p=e.jQuery,
h=function(){},t=Object.prototype.toString,n="function"==typeof HTMLElement||"object"==typeof HTMLElement?function(a){return a instanceof HTMLElement}:function(a){return a&&"object"==typeof a&&1===a.nodeType&&"string"==typeof a.nodeName},w=Array.prototype.indexOf?function(a,b){return a.indexOf(b)}:function(a,b){for(var c=0,d=a.length;d>c;c++)if(a[c]===b)return c;return-1};"function"==typeof define&&define.amd?define("outlayer/outlayer","eventie/eventie doc-ready/doc-ready eventEmitter/EventEmitter get-size/get-size matches-selector/matches-selector ./item".split(" "),
c):"object"==typeof exports?module.exports=c(require("eventie"),require("doc-ready"),require("wolfy87-eventemitter"),require("get-size"),require("desandro-matches-selector"),require("./item")):e.Outlayer=c(e.eventie,e.docReady,e.EventEmitter,e.getSize,e.matchesSelector,e.Outlayer.Item)})(window);
(function(e){function f(e,d){var c=e.create("masonry");return c.prototype._resetLayout=function(){this.getSize();this._getMeasurement("columnWidth","outerWidth");this._getMeasurement("gutter","outerWidth");this.measureColumns();var a=this.cols;for(this.colYs=[];a--;)this.colYs.push(0);this.maxY=0},c.prototype.measureColumns=function(){if(this.getContainerWidth(),!this.columnWidth){var a=this.items[0];this.columnWidth=(a=a&&a.element)&&d(a).outerWidth||this.containerWidth}this.columnWidth+=this.gutter;
this.cols=Math.floor((this.containerWidth+this.gutter)/this.columnWidth);this.cols=Math.max(this.cols,1)},c.prototype.getContainerWidth=function(){var a=d(this.options.isFitWidth?this.element.parentNode:this.element);this.containerWidth=a&&a.innerWidth},c.prototype._getItemLayoutPosition=function(a){a.getSize();var b=a.size.outerWidth%this.columnWidth,b=Math[b&&1>b?"round":"ceil"](a.size.outerWidth/this.columnWidth),b=Math.min(b,this.cols),c=this._getColGroup(b),d=Math.min.apply(Math,c),b=l(c,d),
e={x:this.columnWidth*b,y:d};a=d+a.size.outerHeight;c=this.cols+1-c.length;for(d=0;c>d;d++)this.colYs[b+d]=a;return e},c.prototype._getColGroup=function(a){if(2>a)return this.colYs;for(var b=[],c=this.cols+1-a,d=0;c>d;d++){var e=this.colYs.slice(d,d+a);b[d]=Math.max.apply(Math,e)}return b},c.prototype._manageStamp=function(a){var b=d(a),c=this._getElementOffset(a);a=this.options.isOriginLeft?c.left:c.right;var e=a+b.outerWidth,f=Math.floor(a/this.columnWidth),f=Math.max(0,f);a=Math.floor(e/this.columnWidth);
a-=e%this.columnWidth?0:1;a=Math.min(this.cols-1,a);b=(this.options.isOriginTop?c.top:c.bottom)+b.outerHeight;for(c=f;a>=c;c++)this.colYs[c]=Math.max(b,this.colYs[c])},c.prototype._getContainerSize=function(){this.maxY=Math.max.apply(Math,this.colYs);var a={height:this.maxY};return this.options.isFitWidth&&(a.width=this._getContainerFitWidth()),a},c.prototype._getContainerFitWidth=function(){for(var a=0,b=this.cols;--b&&0===this.colYs[b];)a++;return(this.cols-a)*this.columnWidth-this.gutter},c.prototype.needsResizeLayout=
function(){var a=this.containerWidth;return this.getContainerWidth(),a!==this.containerWidth},c}var l=Array.prototype.indexOf?function(e,d){return e.indexOf(d)}:function(e,d){for(var c=0,a=e.length;a>c;c++)if(e[c]===d)return c;return-1};"function"==typeof define&&define.amd?define(["outlayer/outlayer","get-size/get-size"],f):"object"==typeof exports?module.exports=f(require("outlayer"),require("get-size")):e.Masonry=f(e.Outlayer,e.getSize)})(window);var defensiveInfiniteScroll=$("#entry").hasClass("infinite");
defensiveInfiniteScroll&&function(e){"function"===typeof define&&define.amd?define(["jquery"],e):e(jQuery)}(function(e,f){e.infinitescroll=function(d,c,a){this.element=e(a);this._create(d,c)||(this.failed=!0)};e.infinitescroll.defaults={loading:{finished:f,finishedMsg:"<em>Congratulations, you've reached the end of the internet.</em>",img:null,msg:null,msgText:"<em>Loading the next set of posts...</em>",selector:null,speed:"fast",start:f},state:{isDuringAjax:!1,isInvalidPage:!1,isDestroyed:!1,isDone:!1,
isPaused:!1,isBeyondMaxPage:!1,currPage:1},debug:!1,behavior:f,binder:e(window),nextSelector:"div.navigation a:first",navSelector:"div.navigation",contentSelector:null,extraScrollPx:150,itemSelector:"div.post",animate:!1,pathParse:f,dataType:"html",appendCallback:!0,bufferPx:40,errorCallback:function(){},infid:0,pixelsFromNavToBottom:f,path:f,prefill:!1,maxPage:f};e.infinitescroll.prototype={_binding:function(d){var c=this,a=c.options;a.v="2.0b2.120520";if(a.behavior&&this["_binding_"+a.behavior]!==
f)this["_binding_"+a.behavior].call(this);else{if("bind"!==d&&"unbind"!==d)return this._debug("Binding value  "+d+" not valid"),!1;if("unbind"===d)this.options.binder.unbind("smartscroll.infscr."+c.options.infid);else this.options.binder[d]("smartscroll.infscr."+c.options.infid,function(){c.scroll()});this._debug("Binding",d)}},_create:function(d,c){var a=e.extend(!0,{},e.infinitescroll.defaults,d);this.options=a;var b=e(window);if(!this._validate(d))return!1;var g=e(a.nextSelector).attr("href");
if(!g)return this._debug("Navigation selector not found"),!1;a.path=a.path||this._determinepath(g);a.contentSelector=a.contentSelector||this.element;a.loading.selector=a.loading.selector||a.contentSelector;a.loading.msg=a.loading.msg||e('<div id="infscr-loading"><img alt="Loading..." src="'+a.loading.img+'" /><div>'+a.loading.msgText+"</div></div>");(new Image).src=a.loading.img;a.pixelsFromNavToBottom===f&&(a.pixelsFromNavToBottom=e(document).height()-e(a.navSelector).offset().top,this._debug("pixelsFromNavToBottom: "+
a.pixelsFromNavToBottom));var h=this;a.loading.start=a.loading.start||function(){e(a.navSelector).hide();a.loading.msg.appendTo(a.loading.selector).show(a.loading.speed,e.proxy(function(){this.beginAjax(a)},h))};a.loading.finished=a.loading.finished||function(){a.state.isBeyondMaxPage||a.loading.msg.fadeOut(a.loading.speed)};a.callback=function(d,g,h){a.behavior&&d["_callback_"+a.behavior]!==f&&d["_callback_"+a.behavior].call(e(a.contentSelector)[0],g,h);c&&c.call(e(a.contentSelector)[0],g,a,h);a.prefill&&
b.bind("resize.infinite-scroll",d._prefill)};d.debug&&(!Function.prototype.bind||"object"!==typeof console&&"function"!==typeof console||"object"!==typeof console.log||"log info warn error assert dir clear profile profileEnd".split(" ").forEach(function(a){console[a]=this.call(console[a],console)},Function.prototype.bind));this._setup();a.prefill&&this._prefill();return!0},_prefill:function(){var d=this,c=e(window);this._prefill=function(){e(d.options.contentSelector).height()<=c.height()&&d.scroll();
c.bind("resize.infinite-scroll",function(){e(d.options.contentSelector).height()<=c.height()&&(c.unbind("resize.infinite-scroll"),d.scroll())})};this._prefill()},_debug:function(){!0===this.options.debug&&("undefined"!==typeof console&&"function"===typeof console.log?1===Array.prototype.slice.call(arguments).length&&"string"===typeof Array.prototype.slice.call(arguments)[0]?console.log(Array.prototype.slice.call(arguments).toString()):console.log(Array.prototype.slice.call(arguments)):Function.prototype.bind||
"undefined"===typeof console||"object"!==typeof console.log||Function.prototype.call.call(console.log,console,Array.prototype.slice.call(arguments)))},_determinepath:function(d){var c=this.options;if(c.behavior&&this["_determinepath_"+c.behavior]!==f)return this["_determinepath_"+c.behavior].call(this,d);if(c.pathParse)return this._debug("pathParse manual"),c.pathParse(d,this.options.state.currPage+1);if(d.match(/^(.*?)\b2\b(.*?$)/))d=d.match(/^(.*?)\b2\b(.*?$)/).slice(1);else if(d.match(/^(.*?)2(.*?$)/)){if(d.match(/^(.*?page=)2(\/.*|$)/))return d=
d.match(/^(.*?page=)2(\/.*|$)/).slice(1);d=d.match(/^(.*?)2(.*?$)/).slice(1)}else{if(d.match(/^(.*?page=)1(\/.*|$)/))return d=d.match(/^(.*?page=)1(\/.*|$)/).slice(1);this._debug("Sorry, we couldn't parse your Next (Previous Posts) URL. Verify your the css selector points to the correct A tag. If you still get this error: yell, scream, and kindly ask for help at infinite-scroll.com.");c.state.isInvalidPage=!0}this._debug("determinePath",d);return d},_error:function(d){var c=this.options;c.behavior&&
this["_error_"+c.behavior]!==f?this["_error_"+c.behavior].call(this,d):("destroy"!==d&&"end"!==d&&(d="unknown"),this._debug("Error",d),("end"===d||c.state.isBeyondMaxPage)&&this._showdonemsg(),c.state.isDone=!0,c.state.currPage=1,c.state.isPaused=!1,c.state.isBeyondMaxPage=!1,this._binding("unbind"))},_loadcallback:function(d,c,a){var b=this.options,g=this.options.callback,h=b.state.isDone?"done":b.appendCallback?"append":"no-append";if(b.behavior&&this["_loadcallback_"+b.behavior]!==f)this["_loadcallback_"+
b.behavior].call(this,d,c);else{switch(h){case "done":return this._showdonemsg(),!1;case "no-append":"html"===b.dataType&&(c=e("<div>"+c+"</div>").find(b.itemSelector));if(0===c.length)return this._error("end");break;case "append":h=d.children();if(0===h.length)return this._error("end");for(c=document.createDocumentFragment();d[0].firstChild;)c.appendChild(d[0].firstChild);this._debug("contentSelector",e(b.contentSelector)[0]);e(b.contentSelector)[0].appendChild(c);c=h.get()}b.loading.finished.call(e(b.contentSelector)[0],
b);b.animate&&(d=e(window).scrollTop()+e(b.loading.msg).height()+b.extraScrollPx+"px",e("html,body").animate({scrollTop:d},800,function(){b.state.isDuringAjax=!1}));b.animate||(b.state.isDuringAjax=!1);g(this,c,a);b.prefill&&this._prefill()}},_nearbottom:function(){var d=this.options,c=0+e(document).height()-d.binder.scrollTop()-e(window).height();if(d.behavior&&this["_nearbottom_"+d.behavior]!==f)return this["_nearbottom_"+d.behavior].call(this);this._debug("math:",c,d.pixelsFromNavToBottom);return c-
d.bufferPx<d.pixelsFromNavToBottom},_pausing:function(d){var c=this.options;if(c.behavior&&this["_pausing_"+c.behavior]!==f)this["_pausing_"+c.behavior].call(this,d);else{"pause"!==d&&"resume"!==d&&null!==d&&this._debug("Invalid argument. Toggling pause value instead");switch(!d||"pause"!==d&&"resume"!==d?"toggle":d){case "pause":c.state.isPaused=!0;break;case "resume":c.state.isPaused=!1;break;case "toggle":c.state.isPaused=!c.state.isPaused}this._debug("Paused",c.state.isPaused);return!1}},_setup:function(){var d=
this.options;if(d.behavior&&this["_setup_"+d.behavior]!==f)this["_setup_"+d.behavior].call(this);else return this._binding("bind"),!1},_showdonemsg:function(){var d=this.options;d.behavior&&this["_showdonemsg_"+d.behavior]!==f?this["_showdonemsg_"+d.behavior].call(this):(d.loading.msg.find("img").hide().parent().find("div").html(d.loading.finishedMsg).animate({opacity:1},2E3,function(){e(this).parent().fadeOut(d.loading.speed)}),d.errorCallback.call(e(d.contentSelector)[0],"done"))},_validate:function(d){for(var c in d)if(c.indexOf&&
-1<c.indexOf("Selector")&&0===e(d[c]).length)return this._debug("Your "+c+" found no elements."),!1;return!0},bind:function(){this._binding("bind")},destroy:function(){this.options.state.isDestroyed=!0;this.options.loading.finished();return this._error("destroy")},pause:function(){this._pausing("pause")},resume:function(){this._pausing("resume")},beginAjax:function(d){var c=this,a=d.path,b,g,h;d.state.currPage++;if(d.maxPage!==f&&d.state.currPage>d.maxPage)d.state.isBeyondMaxPage=!0,this.destroy();
else switch(b=e(d.contentSelector).is("table, tbody")?e("<tbody/>"):e("<div/>"),g="function"===typeof a?a(d.state.currPage):a.join(d.state.currPage),c._debug("heading into ajax",g),a="html"===d.dataType||"json"===d.dataType?d.dataType:"html+callback",d.appendCallback&&"html"===d.dataType&&(a+="+callback"),a){case "html+callback":c._debug("Using HTML via .load() method");b.load(g+" "+d.itemSelector,f,function(a){c._loadcallback(b,a,g)});break;case "html":c._debug("Using "+a.toUpperCase()+" via $.ajax() method");
e.ajax({url:g,dataType:d.dataType,complete:function(a,d){(h="undefined"!==typeof a.isResolved?a.isResolved():"success"===d||"notmodified"===d)?c._loadcallback(b,a.responseText,g):c._error("end")}});break;case "json":c._debug("Using "+a.toUpperCase()+" via $.ajax() method"),e.ajax({dataType:"json",type:"GET",url:g,success:function(a,e,l){h="undefined"!==typeof l.isResolved?l.isResolved():"success"===e||"notmodified"===e;d.appendCallback?d.template!==f?(a=d.template(a),b.append(a),h?c._loadcallback(b,
a):c._error("end")):(c._debug("template must be defined."),c._error("end")):h?c._loadcallback(b,a,g):c._error("end")},error:function(){c._debug("JSON ajax request failed.");c._error("end")}})}},retrieve:function(d){d=d||null;var c=this.options;if(c.behavior&&this["retrieve_"+c.behavior]!==f)this["retrieve_"+c.behavior].call(this,d);else{if(c.state.isDestroyed)return this._debug("Instance is destroyed"),!1;c.state.isDuringAjax=!0;c.loading.start.call(e(c.contentSelector)[0],c)}},scroll:function(){var d=
this.options,c=d.state;d.behavior&&this["scroll_"+d.behavior]!==f?this["scroll_"+d.behavior].call(this):c.isDuringAjax||c.isInvalidPage||c.isDone||c.isDestroyed||c.isPaused||this._nearbottom()&&this.retrieve()},toggle:function(){this._pausing()},unbind:function(){this._binding("unbind")},update:function(d){e.isPlainObject(d)&&(this.options=e.extend(!0,this.options,d))}};e.fn.infinitescroll=function(d,c){switch(typeof d){case "string":var a=Array.prototype.slice.call(arguments,1);this.each(function(){var b=
e.data(this,"infinitescroll");if(!b||!e.isFunction(b[d])||"_"===d.charAt(0))return!1;b[d].apply(b,a)});break;case "object":this.each(function(){var a=e.data(this,"infinitescroll");a?a.update(d):(a=new e.infinitescroll(d,c,this),a.failed||e.data(this,"infinitescroll",a))})}return this};var l=e.event,g;l.special.smartscroll={setup:function(){e(this).bind("scroll",l.special.smartscroll.handler)},teardown:function(){e(this).unbind("scroll",l.special.smartscroll.handler)},handler:function(d,c){var a=this,
b=arguments;d.type="smartscroll";g&&clearTimeout(g);g=setTimeout(function(){e(a).trigger("smartscroll",b)},"execAsap"===c?0:100)}};e.fn.smartscroll=function(d){return d?this.bind("smartscroll",d):this.trigger("smartscroll",["execAsap"])}});
$(function(){$("nav").append('<a target="_blank" class="nav" href="http://rowrz.com/themes">theme</a>');$("body").prepend('<a id="install-btn" href="https://tumblr.com/theme/38849" title="Install This Theme" target="_blank" style="opacity: 1;"><span id="install-btn-txt">Install Theme</span></a>');setTimeout(function(){$("#install-btn").animate({top:"3px"})},1E3);$.fn.photosetResize=function(){$(this).each(function(){var e=$(".posts").width(),l=$(this).attr("src").replace("500",e);$(this).attr("src",
l).width(e);l=$(this).css("height");e=parseInt(l,10)*e/500;$(this).css("height",e)});return this};var e=$("#posts");$("iframe.photoset").photosetResize();e.imagesLoaded(function(){e.masonry({itemSelector:"#entry",isResizable:!0})});defensiveInfiniteScroll&&e.infinitescroll({navSelector:"#page-nav",nextSelector:"#page-nav a",itemSelector:"#entry",loadingImg:"",loadingText:"",bufferPx:100,extraScrollPx:200,loading:{finishedMsg:""}},function(f){$(f).find("iframe.photoset").photosetResize();$(f).hide().imagesLoaded(function(){e.masonry("appended",
$(f).show())})})});
window.Modernizr=function(e,f,l){function g(a,b){return typeof a===b}function d(a,b){for(var c in a){var d=a[c];if(!~(""+d).indexOf("-")&&t[d]!==l)return"pfx"==b?d:!0}return!1}function c(a,b,c){var e=a.charAt(0).toUpperCase()+a.slice(1),f=(a+" "+B.join(e+" ")+e).split(" ");if(g(b,"string")||g(b,"undefined"))b=d(f,b);else a:{f=(a+" "+v.join(e+" ")+e).split(" "),a=f;for(var h in a)if(e=b[a[h]],e!==l){b=!1===c?a[h]:g(e,"function")?e.bind(c||b):e;break a}b=!1}return b}function a(){b.input=function(a){for(var b=
0,c=a.length;b<c;b++)z[a[b]]=a[b]in n;return z.list&&(z.list=!!f.createElement("datalist")&&!!e.HTMLDataListElement),z}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));b.inputtypes=function(a){for(var b=0,c,d,e,g=a.length;b<g;b++)n.setAttribute("type",d=a[b]),(c="text"!==n.type)&&(n.value=w,n.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(d)&&n.style.WebkitAppearance!==l?(p.appendChild(n),e=f.defaultView,c=e.getComputedStyle&&"textfield"!==
e.getComputedStyle(n,null).WebkitAppearance&&0!==n.offsetHeight,p.removeChild(n)):/^(search|tel)$/.test(d)||(/^(url|email)$/.test(d)?c=n.checkValidity&&!1===n.checkValidity():c=n.value!=w)),C[a[b]]=!!c;return C}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var b={},p=f.documentElement,h=f.createElement("modernizr"),t=h.style,n=f.createElement("input"),w=":)",A={}.toString,m=" -webkit- -moz- -o- -ms- ".split(" "),B=["Webkit","Moz","O","ms"],v=["webkit",
"moz","o","ms"],h={},C={},z={},k=[],u=k.slice,x,y=function(a,b,c,d){var e,g,h,l,k=f.createElement("div"),m=f.body,r=m||f.createElement("body");if(parseInt(c,10))for(;c--;)h=f.createElement("div"),h.id=d?d[c]:"modernizr"+(c+1),k.appendChild(h);return e=['&#173;<style id="smodernizr">',a,"</style>"].join(""),k.id="modernizr",(m?k:r).innerHTML+=e,r.appendChild(k),m||(r.style.background="",r.style.overflow="hidden",l=p.style.overflow,p.style.overflow="hidden",p.appendChild(r)),g=b(k,a),m?k.parentNode.removeChild(k):
(r.parentNode.removeChild(r),p.style.overflow=l),!!g},q=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,c){c=c||f.createElement(a[b]||"div");b="on"+b;var d=b in c;return d||(c.setAttribute||(c=f.createElement("div")),c.setAttribute&&c.removeAttribute&&(c.setAttribute(b,""),d=g(c[b],"function"),g(c[b],"undefined")||(c[b]=l),c.removeAttribute(b))),d}}(),r={}.hasOwnProperty,F;g(r,"undefined")||g(r.call,"undefined")?F=function(a,
b){return b in a&&g(a.constructor.prototype[b],"undefined")}:F=function(a,b){return r.call(a,b)};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;var c=u.call(arguments,1),d=function(){if(this instanceof d){var e=function(){};e.prototype=b.prototype;var e=new e,f=b.apply(e,c.concat(u.call(arguments)));return Object(f)===f?f:e}return b.apply(a,c.concat(u.call(arguments)))};return d});h.flexbox=function(){return c("flexWrap")};h.canvas=
function(){var a=f.createElement("canvas");return!!a.getContext&&!!a.getContext("2d")};h.canvastext=function(){return!!b.canvas&&!!g(f.createElement("canvas").getContext("2d").fillText,"function")};h.webgl=function(){return!!e.WebGLRenderingContext};h.touch=function(){var a;return"ontouchstart"in e||e.DocumentTouch&&f instanceof DocumentTouch?a=!0:y(["@media (",m.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),function(b){a=9===b.offsetTop}),a};h.geolocation=
function(){return"geolocation"in navigator};h.postmessage=function(){return!!e.postMessage};h.websqldatabase=function(){return!!e.openDatabase};h.indexedDB=function(){return!!c("indexedDB",e)};h.hashchange=function(){return q("hashchange",e)&&(f.documentMode===l||7<f.documentMode)};h.history=function(){return!!e.history&&!!history.pushState};h.draganddrop=function(){var a=f.createElement("div");return"draggable"in a||"ondragstart"in a&&"ondrop"in a};h.websockets=function(){return"WebSocket"in e||
"MozWebSocket"in e};h.rgba=function(){t.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+t.backgroundColor).indexOf("rgba")};h.hsla=function(){t.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+t.backgroundColor).indexOf("rgba")||!!~(""+t.backgroundColor).indexOf("hsla")};h.multiplebgs=function(){t.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(t.background)};h.backgroundsize=function(){return c("backgroundSize")};h.borderimage=
function(){return c("borderImage")};h.borderradius=function(){return c("borderRadius")};h.boxshadow=function(){return c("boxShadow")};h.textshadow=function(){return""===f.createElement("div").style.textShadow};h.opacity=function(){var a=m.join("opacity:.55;")+"";t.cssText=a;return/^0.55$/.test(t.opacity)};h.cssanimations=function(){return c("animationName")};h.csscolumns=function(){return c("columnCount")};h.cssgradients=function(){var a=("background-image:-webkit-gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:"+
m.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);t.cssText=a;return!!~(""+t.backgroundImage).indexOf("gradient")};h.cssreflections=function(){return c("boxReflect")};h.csstransforms=function(){return!!c("transform")};h.csstransforms3d=function(){var a=!!c("perspective");return a&&"webkitPerspective"in p.style&&y("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b,c){a=9===b.offsetLeft&&3===b.offsetHeight}),a};
h.csstransitions=function(){return c("transition")};h.fontface=function(){var a;return y('@font-face {font-family:"font";src:url("https://")}',function(b,c){var d=f.getElementById("smodernizr"),d=(d=d.sheet||d.styleSheet)?d.cssRules&&d.cssRules[0]?d.cssRules[0].cssText:d.cssText||"":"";a=/src/i.test(d)&&0===d.indexOf(c.split(" ")[0])}),a};h.generatedcontent=function(){var a;return y(['#modernizr{font:0/0 a}#modernizr:after{content:"',w,'";visibility:hidden;font:3px/1 a}'].join(""),function(b){a=3<=
b.offsetHeight}),a};h.video=function(){var a=f.createElement("video"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(c){}return b};h.audio=function(){var a=f.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,
""),b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(c){}return b};h.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(a){return!1}};h.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(a){return!1}};
h.webworkers=function(){return!!e.Worker};h.applicationcache=function(){return!!e.applicationCache};h.svg=function(){return!!f.createElementNS&&!!f.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};h.inlinesvg=function(){var a=f.createElement("div");return a.innerHTML="<svg/>","http://www.w3.org/2000/svg"==(a.firstChild&&a.firstChild.namespaceURI)};h.smil=function(){return!!f.createElementNS&&/SVGAnimate/.test(A.call(f.createElementNS("http://www.w3.org/2000/svg","animate")))};h.svgclippaths=
function(){return!!f.createElementNS&&/SVGClipPath/.test(A.call(f.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var G in h)F(h,G)&&(x=G.toLowerCase(),b[x]=h[G](),k.push((b[x]?"":"no-")+x));b.input||a();b.addTest=function(a,c){if("object"==typeof a)for(var d in a)F(a,d)&&b.addTest(d,a[d]);else{a=a.toLowerCase();if(b[a]!==l)return b;c="function"==typeof c?c():c;p.className+=" "+(c?"":"no-")+a;b[a]=c}return b};t.cssText="";return h=n=null,function(a,b){function c(){var a=p.elements;
return"string"==typeof a?a.split(" "):a}function d(a){var b=y[a[m]];return b||(b={},n++,a[m]=n,y[n]=b),b}function e(a,c,f){c||(c=b);if(q)return c.createElement(a);f||(f=d(c));var g;return f.cache[a]?g=f.cache[a].cloneNode():k.test(a)?g=(f.cache[a]=f.createElem(a)).cloneNode():g=f.createElem(a),g.canHaveChildren&&!l.test(a)?f.frag.appendChild(g):g}function f(a,b){b.cache||(b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag());a.createElement=function(c){return p.shivMethods?
e(c,a,b):b.createElem(c)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+c().join().replace(/\w+/g,function(a){return b.createElem(a),b.frag.createElement(a),'c("'+a+'")'})+");return n}")(p,b.frag)}function g(a){a||(a=b);var c=d(a);if(p.shivCSS&&!r&&!c.hasCSS){var e,h=a;e=h.createElement("p");h=h.getElementsByTagName("head")[0]||h.documentElement;e=(e.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>",
h.insertBefore(e.lastChild,h.firstChild));c.hasCSS=!!e}return q||f(a,c),a}var h=a.html5||{},l=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,k=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,r,m="_html5shiv",n=0,y={},q;(function(){try{var a=b.createElement("a");a.innerHTML="<xyz></xyz>";r="hidden"in a;var c;if(!(c=1==a.childNodes.length)){b.createElement("a");var d=b.createDocumentFragment();c="undefined"==typeof d.cloneNode||
"undefined"==typeof d.createDocumentFragment||"undefined"==typeof d.createElement}q=c}catch(e){q=r=!0}})();var p={elements:h.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==h.shivCSS,supportsUnknownElements:q,shivMethods:!1!==h.shivMethods,type:"default",shivDocument:g,createElement:e,createDocumentFragment:function(a,e){a||(a=b);if(q)return a.createDocumentFragment();
e=e||d(a);for(var f=e.frag.cloneNode(),g=0,h=c(),l=h.length;g<l;g++)f.createElement(h[g]);return f}};a.html5=p;g(b)}(this,f),b._version="2.6.2",b._prefixes=m,b._domPrefixes=v,b._cssomPrefixes=B,b.mq=function(a){var b=e.matchMedia||e.msMatchMedia;if(b)return b(a).matches;var c;return y("@media "+a+" { #modernizr { position: absolute; } }",function(a){c="absolute"==(e.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position}),c},b.hasEvent=q,b.testProp=function(a){return d([a])},b.testAllProps=
c,b.testStyles=y,b.prefixed=function(a,b,d){return b?c(a,b,d):c(a,"pfx")},p.className=p.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+k.join(" ")),b}(this,this.document);
(function(e,f,l){function g(a){return"[object Function]"==m.call(a)}function d(a){return"string"==typeof a}function c(){}function a(a){return!a||"loaded"==a||"complete"==a||"uninitialized"==a}function b(){var a=B.shift();v=1;a?a.t?w(function(){("c"==a.t?D.injectCss:D.injectJs)(a.s,0,a.a,a.x,a.e,1)},0):(a(),b()):v=0}function p(c,d,e,g,h,l,m){function n(e){if(!y&&a(q.readyState)&&(t.r=y=1,!v&&b(),q.onload=q.onreadystatechange=null,e)){"img"!=c&&w(function(){k.removeChild(q)},50);for(var f in r[d])r[d].hasOwnProperty(f)&&
r[d][f].onload()}}m=m||D.errorTimeout;var q=f.createElement(c),y=0,p=0,t={t:e,s:d,e:h,a:l,x:m};1===r[d]&&(p=1,r[d]=[]);"object"==c?q.data=d:(q.src=d,q.type=c);q.width=q.height="0";q.onerror=q.onload=q.onreadystatechange=function(){n.call(this,p)};B.splice(g,0,t);"img"!=c&&(p||2===r[d]?(k.insertBefore(q,z?null:A),w(n,m)):r[d].push(q))}function h(a,c,e,f,g){return v=0,c=c||"j",d(a)?p("c"==c?x:u,a,c,this.i++,e,f,g):(B.splice(this.i++,0,a),1==B.length&&b()),this}function t(){var a=D;return a.loader={load:h,
i:0},a}var n=f.documentElement,w=e.setTimeout,A=f.getElementsByTagName("script")[0],m={}.toString,B=[],v=0,C="MozAppearance"in n.style,z=C&&!!f.createRange().compareNode,k=z?n:A.parentNode,n=e.opera&&"[object Opera]"==m.call(e.opera),n=!!f.attachEvent&&!n,u=C?"object":n?"script":"img",x=n?"script":u,y=Array.isArray||function(a){return"[object Array]"==m.call(a)},q=[],r={},F={timeout:function(a,b){return b.length&&(a.timeout=b[0]),a}},G,D;D=function(a){function b(a){a=a.split("!");var c=q.length,d=
a.pop(),e=a.length,d={url:d,origUrl:d,prefixes:a},f,g,h;for(g=0;g<e;g++)h=a[g].split("="),(f=F[h.shift()])&&(d=f(d,h));for(g=0;g<c;g++)d=q[g](d);return d}function e(a,c,d,f,h){var k=b(a),m=k.autoCallback;k.url.split(".").pop().split("?").shift();k.bypass||(c&&(c=g(c)?c:c[a]||c[f]||c[a.split("/").pop().split("?")[0]]),k.instead?k.instead(a,c,d,f,h):(r[k.url]?k.noexec=!0:r[k.url]=1,d.load(k.url,k.forceCSS||!k.forceJS&&"css"==k.url.split(".").pop().split("?").shift()?"c":l,k.noexec,k.attrs,k.timeout),
(g(c)||g(m))&&d.load(function(){t();c&&c(k.origUrl,h,f);m&&m(k.origUrl,h,f);r[k.url]=2})))}function f(a,b){function h(a,c){if(a)if(d(a))c||(m=function(){var a=[].slice.call(arguments);r.apply(this,a);q()}),e(a,m,b,0,k);else{if(Object(a)===a)for(y in n=function(){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(),a)a.hasOwnProperty(y)&&(!c&&!--n&&(g(m)?m=function(){var a=[].slice.call(arguments);r.apply(this,a);q()}:m[y]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b);q()}}(r[y])),e(a[y],m,b,y,k))}else!c&&q()}var k=!!a.test,l=a.load||a.both,m=a.callback||c,r=m,q=a.complete||c,n,y;h(k?a.yep:a.nope,!!l);l&&h(l)}var h,k,m=this.yepnope.loader;if(d(a))e(a,0,m,0);else if(y(a))for(h=0;h<a.length;h++)k=a[h],d(k)?e(k,0,m,0):y(k)?D(k):Object(k)===k&&f(k,m);else Object(a)===a&&f(a,m)};D.addPrefix=function(a,b){F[a]=b};D.addFilter=function(a){q.push(a)};D.errorTimeout=1E4;null==f.readyState&&f.addEventListener&&(f.readyState="loading",f.addEventListener("DOMContentLoaded",
G=function(){f.removeEventListener("DOMContentLoaded",G,0);f.readyState="complete"},0));e.yepnope=t();e.yepnope.executeStack=b;e.yepnope.injectJs=function(d,e,g,h,k,l){var m=f.createElement("script"),r,q;h=h||D.errorTimeout;m.src=d;for(q in g)m.setAttribute(q,g[q]);e=l?b:e||c;m.onreadystatechange=m.onload=function(){!r&&a(m.readyState)&&(r=1,e(),m.onload=m.onreadystatechange=null)};w(function(){r||(r=1,e(1))},h);k?m.onload():A.parentNode.insertBefore(m,A)};e.yepnope.injectCss=function(a,d,e,g,h,k){g=
f.createElement("link");var l;d=k?b:d||c;g.href=a;g.rel="stylesheet";g.type="text/css";for(l in e)g.setAttribute(l,e[l]);h||(A.parentNode.insertBefore(g,A),w(d,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
window.matchMedia=window.matchMedia||function(e,f){var l,g=e.documentElement,d=g.firstElementChild||g.firstChild,c=e.createElement("body"),a=e.createElement("div");a.id="mq-test-1";a.style.cssText="position:absolute;top:-100em";c.style.background="none";c.appendChild(a);return function(b){a.innerHTML='&shy;<style media="'+b+'"> #mq-test-1 { width: 42px; }</style>';g.insertBefore(c,d);l=42==a.offsetWidth;g.removeChild(c);return{matches:l,media:b}}}(document);
(function(e){function f(){k(!0)}e.respond={};respond.update=function(){};respond.mediaQueriesSupported=e.matchMedia&&e.matchMedia("only all").matches;if(!respond.mediaQueriesSupported){var l=e.document,g=l.documentElement,d=[],c=[],a=[],b={},p=l.getElementsByTagName("head")[0]||g,h=l.getElementsByTagName("base")[0],t=p.getElementsByTagName("link"),n=[],w=function(){for(var a=t.length,c=0,d,f,g,k;c<a;c++)d=t[c],f=d.href,g=d.media,k=d.rel&&"stylesheet"===d.rel.toLowerCase(),f&&k&&!b[f]&&(d.styleSheet&&
d.styleSheet.rawCssText?(m(d.styleSheet.rawCssText,f,g),b[f]=!0):(/^([a-zA-Z:]*\/\/)/.test(f)||h)&&f.replace(RegExp.$1,"").split("/")[0]!==e.location.host||n.push({href:f,media:g}));A()},A=function(){if(n.length){var a=n.shift();u(a.href,function(c){m(c,a.href,a.media);b[a.href]=!0;A()})}},m=function(a,b,e){var f=a.match(/@media[^\{]+\{([^\{\}]*\{[^\}\{]*\})+/gi),g=f&&f.length||0;b=b.substring(0,b.lastIndexOf("/"));var h=function(a){return a.replace(/(url\()['"]?([^\/\)'"][^:\)'"]+)['"]?(\))/g,"$1"+
b+"$2$3")},l=!g&&e,m=0,n,p,t,v;b.length&&(b+="/");for(l&&(g=1);m<g;m++)for(n=0,l?(p=e,c.push(h(a))):(p=f[m].match(/@media *([^\{]+)\{([\S\s]+?)$/)&&RegExp.$1,c.push(RegExp.$2&&h(RegExp.$2))),t=p.split(","),v=t.length;n<v;n++)p=t[n],d.push({media:p.split("(")[0].match(/(only\s+)?([a-zA-Z]+)\s?/)&&RegExp.$2||"all",rules:c.length-1,hasquery:-1<p.indexOf("("),minw:p.match(/\(min\-width:[\s]*([\s]*[0-9\.]+)(px|em)[\s]*\)/)&&parseFloat(RegExp.$1)+(RegExp.$2||""),maxw:p.match(/\(max\-width:[\s]*([\s]*[0-9\.]+)(px|em)[\s]*\)/)&&
parseFloat(RegExp.$1)+(RegExp.$2||"")});k()},B,v,C=function(){var a,b=l.createElement("div"),c=l.body,d=!1;b.style.cssText="position:absolute;font-size:1em;width:1em";c||(c=d=l.createElement("body"),c.style.background="none");c.appendChild(b);g.insertBefore(c,g.firstChild);a=b.offsetWidth;d?g.removeChild(c):c.removeChild(b);return a=z=parseFloat(a)},z,k=function(b){var e=g.clientWidth,f="CSS1Compat"===l.compatMode&&e||l.body.clientWidth||e,e={},h=t[t.length-1],m=(new Date).getTime();if(b&&B&&30>m-
B)clearTimeout(v),v=setTimeout(k,30);else{B=m;for(var n in d){b=d[n];var m=b.minw,u=b.maxw,w=null===m,x=null===u;m&&(m=parseFloat(m)*(-1<m.indexOf("em")?z||C():1));u&&(u=parseFloat(u)*(-1<u.indexOf("em")?z||C():1));b.hasquery&&(w&&x||!(w||f>=m)||!(x||f<=u))||(e[b.media]||(e[b.media]=[]),e[b.media].push(c[b.rules]))}for(n in a)a[n]&&a[n].parentNode===p&&p.removeChild(a[n]);for(n in e)f=l.createElement("style"),b=e[n].join("\n"),f.type="text/css",f.media=n,p.insertBefore(f,h.nextSibling),f.styleSheet?
f.styleSheet.cssText=b:f.appendChild(l.createTextNode(b)),a.push(f)}},u=function(a,b){var c=x();c&&(c.open("GET",a,!0),c.onreadystatechange=function(){4!=c.readyState||200!=c.status&&304!=c.status||b(c.responseText)},4!=c.readyState&&c.send(null))},x=function(){var a=!1;try{a=new XMLHttpRequest}catch(b){a=new ActiveXObject("Microsoft.XMLHTTP")}return function(){return a}}();w();respond.update=w;e.addEventListener?e.addEventListener("resize",f,!1):e.attachEvent&&e.attachEvent("onresize",f)}})(this);